apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: sdsd123654/kafka-connect-debezium
          imagePullPolicy: IfNotPresent
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "kafka-srv:9092"

            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: "kafka-connect-srv"

            - name: CONNECT_GROUP_ID
              value: "kafka-connect"

            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "_connect-configs"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "_connect-offsets"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "_connect-status"

            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              value: "1"
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              value: "1"

            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/java"

            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
              value: "false"
            - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
              value: "false"

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: orders-postgres-credentials
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-postgres-credentials
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-srv
spec:
  selector:
    app: kafka-connect
  ports:
    - name: connect
      port: 8083
      targetPort: 8083
      protocol: TCP
