apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-postgres
  template:
    metadata:
      labels:
        app: orders-postgres
    spec:
      containers:
        - name: orders-postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: orders-postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orders-postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: 'orders'
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: orders-postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: orders-postgres-storage
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: orders-postgres-srv
spec:
  type: NodePort
  selector:
    app: orders-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 32543
